config/routes.rb
Rails.application.routes.draw do
  resources :itens
  get 'home/index'
  devise_for :users
  resources :brunoagendas
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appwebexemp.rb
class Appwebexemp < ApplicationRecord
end

app/models/brunoagenda.rb
class Brunoagenda < ApplicationRecord
end

app/models/iten.rb
class Iten < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/brunoagendas_controller.rb
class BrunoagendasController < ApplicationController
  before_action :set_brunoagenda, only: %i[ show edit update destroy ]

  # GET /brunoagendas or /brunoagendas.json
  def index
    @brunoagendas = Brunoagenda.all
  end

  # GET /brunoagendas/1 or /brunoagendas/1.json
  def show
  end

  # GET /brunoagendas/new
  def new
    @brunoagenda = Brunoagenda.new
  end

  # GET /brunoagendas/1/edit
  def edit
  end

  # POST /brunoagendas or /brunoagendas.json
  def create
    @brunoagenda = Brunoagenda.new(brunoagenda_params)

    respond_to do |format|
      if @brunoagenda.save
        format.html { redirect_to @brunoagenda, notice: "Brunoagenda was successfully created." }
        format.json { render :show, status: :created, location: @brunoagenda }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @brunoagenda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brunoagendas/1 or /brunoagendas/1.json
  def update
    respond_to do |format|
      if @brunoagenda.update(brunoagenda_params)
        format.html { redirect_to @brunoagenda, notice: "Brunoagenda was successfully updated." }
        format.json { render :show, status: :ok, location: @brunoagenda }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @brunoagenda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brunoagendas/1 or /brunoagendas/1.json
  def destroy
    @brunoagenda.destroy
    respond_to do |format|
      format.html { redirect_to brunoagendas_url, notice: "Brunoagenda was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brunoagenda
      @brunoagenda = Brunoagenda.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def brunoagenda_params
      params.require(:brunoagenda).permit(:nome, :id_seq, :endereco, :preco, :email)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/itens_controller.rb
class ItensController < ApplicationController
  before_action :set_iten, only: %i[ show edit update destroy ]

  # GET /itens or /itens.json
  def index
    @itens = Iten.all
  end

  # GET /itens/1 or /itens/1.json
  def show
  end

  # GET /itens/new
  def new
    @iten = Iten.new
  end

  # GET /itens/1/edit
  def edit
  end

  # POST /itens or /itens.json
  def create
    @iten = Iten.new(iten_params)

    respond_to do |format|
      if @iten.save
        format.html { redirect_to @iten, notice: "Iten was successfully created." }
        format.json { render :show, status: :created, location: @iten }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @iten.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /itens/1 or /itens/1.json
  def update
    respond_to do |format|
      if @iten.update(iten_params)
        format.html { redirect_to @iten, notice: "Iten was successfully updated." }
        format.json { render :show, status: :ok, location: @iten }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @iten.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /itens/1 or /itens/1.json
  def destroy
    @iten.destroy
    respond_to do |format|
      format.html { redirect_to itens_url, notice: "Iten was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_iten
      @iten = Iten.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def iten_params
      params.require(:iten).permit(:nome, :id_seq, :modelo, :quantidade, :level)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appwebexemps_helper.rb
module AppwebexempsHelper
end

app/helpers/brunoagendas_helper.rb
module BrunoagendasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/itens_helper.rb
module ItensHelper
end

app/views/appwebexemps/_form.html.erb
<%= form_with(model: appwebexemp) do |form| %>
  <% if appwebexemp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appwebexemp.errors.count, "error") %> prohibited this appwebexemp from being saved:</h2>

      <ul>
        <% appwebexemp.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :id %>
    <%= form.text_field :id %>
  </div>

  <div class="field">
    <%= form.label :endereco %>
    <%= form.text_area :endereco %>
  </div>

  <div class="field">
    <%= form.label :sobrenome %>
    <%= form.text_field :sobrenome %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/appwebexemps/edit.html.erb
<h1>Editing Appwebexemp</h1>

<%= render 'form', appwebexemp: @appwebexemp %>

<%= link_to 'Show', @appwebexemp %> |
<%= link_to 'Back', appwebexemps_path %>

app/views/appwebexemps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appwebexemps</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Id</th>
      <th>Endereco</th>
      <th>Sobrenome</th>
      <th>Email</th>
      <th>Telefone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appwebexemps.each do |appwebexemp| %>
      <tr>
        <td><%= appwebexemp.nome %></td>
        <td><%= appwebexemp.id %></td>
        <td><%= appwebexemp.endereco %></td>
        <td><%= appwebexemp.sobrenome %></td>
        <td><%= appwebexemp.email %></td>
        <td><%= appwebexemp.telefone %></td>
        <td><%= link_to 'Show', appwebexemp %></td>
        <td><%= link_to 'Edit', edit_appwebexemp_path(appwebexemp) %></td>
        <td><%= link_to 'Destroy', appwebexemp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appwebexemp', new_appwebexemp_path %>

app/views/appwebexemps/new.html.erb
<h1>New Appwebexemp</h1>

<%= render 'form', appwebexemp: @appwebexemp %>

<%= link_to 'Back', appwebexemps_path %>

app/views/appwebexemps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @appwebexemp.nome %>
</p>

<p>
  <strong>Id:</strong>
  <%= @appwebexemp.id %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @appwebexemp.endereco %>
</p>

<p>
  <strong>Sobrenome:</strong>
  <%= @appwebexemp.sobrenome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @appwebexemp.email %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @appwebexemp.telefone %>
</p>

<%= link_to 'Edit', edit_appwebexemp_path(@appwebexemp) %> |
<%= link_to 'Back', appwebexemps_path %>

app/views/brunoagendas/_form.html.erb
<%= form_with(model: brunoagenda) do |form| %>
  <% if brunoagenda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brunoagenda.errors.count, "error") %> prohibited this brunoagenda from being saved:</h2>

      <ul>
        <% brunoagenda.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :id_seq %>
    <%= form.text_field :id_seq %>
  </div>

  <div class="field">
    <%= form.label :endereco %>
    <%= form.text_area :endereco %>
  </div>

  <div class="field">
    <%= form.label :preco %>
    <%= form.text_field :preco %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/brunoagendas/edit.html.erb
<h1>Editing Brunoagenda</h1>

<%= render 'form', brunoagenda: @brunoagenda %>

<%= link_to 'Show', @brunoagenda %> |
<%= link_to 'Back', brunoagendas_path %>

app/views/brunoagendas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Brunoagendas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Id seq</th>
      <th>Endereco</th>
      <th>Preco</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brunoagendas.each do |brunoagenda| %>
      <tr>
        <td><%= brunoagenda.nome %></td>
        <td><%= brunoagenda.id_seq %></td>
        <td><%= brunoagenda.endereco %></td>
        <td><%= brunoagenda.preco %></td>
        <td><%= brunoagenda.email %></td>
        <td><%= link_to 'Show', brunoagenda %></td>
        <td><%= link_to 'Edit', edit_brunoagenda_path(brunoagenda) %></td>
        <td><%= link_to 'Destroy', brunoagenda, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brunoagenda', new_brunoagenda_path %>

app/views/brunoagendas/new.html.erb
<h1>New Brunoagenda</h1>

<%= render 'form', brunoagenda: @brunoagenda %>

<%= link_to 'Back', brunoagendas_path %>

app/views/brunoagendas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @brunoagenda.nome %>
</p>

<p>
  <strong>Id seq:</strong>
  <%= @brunoagenda.id_seq %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @brunoagenda.endereco %>
</p>

<p>
  <strong>Preco:</strong>
  <%= @brunoagenda.preco %>
</p>

<p>
  <strong>Email:</strong>
  <%= @brunoagenda.email %>
</p>

<%= link_to 'Edit', edit_brunoagenda_path(@brunoagenda) %> |
<%= link_to 'Back', brunoagendas_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<%= link_to "Sair", destroy_user_session_path, method: :delete %>
<%= link_to "Perfil", edit_user_registration_path %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/itens/_form.html.erb
<%= form_with(model: iten) do |form| %>
  <% if iten.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(iten.errors.count, "error") %> prohibited this iten from being saved:</h2>

      <ul>
        <% iten.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :id_seq %>
    <%= form.text_field :id_seq %>
  </div>

  <div class="field">
    <%= form.label :modelo %>
    <%= form.text_area :modelo %>
  </div>

  <div class="field">
    <%= form.label :quantidade %>
    <%= form.text_field :quantidade %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.text_field :level %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/itens/edit.html.erb
<h1>Editing Iten</h1>

<%= render 'form', iten: @iten %>

<%= link_to 'Show', @iten %> |
<%= link_to 'Back', itens_path %>

app/views/itens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Itens</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Id seq</th>
      <th>Modelo</th>
      <th>Quantidade</th>
      <th>Level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @itens.each do |iten| %>
      <tr>
        <td><%= iten.nome %></td>
        <td><%= iten.id_seq %></td>
        <td><%= iten.modelo %></td>
        <td><%= iten.quantidade %></td>
        <td><%= iten.level %></td>
        <td><%= link_to 'Show', iten %></td>
        <td><%= link_to 'Edit', edit_iten_path(iten) %></td>
        <td><%= link_to 'Destroy', iten, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Iten', new_iten_path %>

app/views/itens/new.html.erb
<h1>New Iten</h1>

<%= render 'form', iten: @iten %>

<%= link_to 'Back', itens_path %>

app/views/itens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @iten.nome %>
</p>

<p>
  <strong>Id seq:</strong>
  <%= @iten.id_seq %>
</p>

<p>
  <strong>Modelo:</strong>
  <%= @iten.modelo %>
</p>

<p>
  <strong>Quantidade:</strong>
  <%= @iten.quantidade %>
</p>

<p>
  <strong>Level:</strong>
  <%= @iten.level %>
</p>

<%= link_to 'Edit', edit_iten_path(@iten) %> |
<%= link_to 'Back', itens_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Agendinha</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>